services:
  - type: web
    name: interview-transcription-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false 